/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_enquery_encryptedquery_querier_wideskies_encrypt_EncryptQueryFixedBaseWithJNITask */

#ifndef _Included_org_enquery_encryptedquery_querier_wideskies_encrypt_EncryptQueryFixedBaseWithJNITask
#define _Included_org_enquery_encryptedquery_querier_wideskies_encrypt_EncryptQueryFixedBaseWithJNITask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_enquery_encryptedquery_querier_wideskies_encrypt_EncryptQueryFixedBaseWithJNITask
 * Method:    encrypt
 * Signature: (JI[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_enquery_encryptedquery_querier_wideskies_encrypt_EncryptQueryFixedBaseWithJNITask_encrypt
  (JNIEnv *, jobject, jlong, jint, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_enquery_encryptedquery_querier_wideskies_encrypt_EncryptQueryFixedBaseWithJNITaskFactory */

#ifndef _Included_org_enquery_encryptedquery_querier_wideskies_encrypt_EncryptQueryFixedBaseWithJNITaskFactory
#define _Included_org_enquery_encryptedquery_querier_wideskies_encrypt_EncryptQueryFixedBaseWithJNITaskFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_enquery_encryptedquery_querier_wideskies_encrypt_EncryptQueryFixedBaseWithJNITaskFactory
 * Method:    newContext
 * Signature: ([B[B[B[BIII)J
 */
JNIEXPORT jlong JNICALL Java_org_enquery_encryptedquery_querier_wideskies_encrypt_EncryptQueryFixedBaseWithJNITaskFactory_newContext
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
