/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI */

#ifndef _Included_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI
#define _Included_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI
 * Method:    derooijNew
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI_derooijNew
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI
 * Method:    derooijSetQueryElement
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI_derooijSetQueryElement
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI
 * Method:    derooijInsertDataPart
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI_derooijInsertDataPart
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI
 * Method:    derooijInsertDataPart2
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI_derooijInsertDataPart2
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI
 * Method:    derooijComputeColumnAndClearData
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI_derooijComputeColumnAndClearData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI
 * Method:    derooijClearData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI_derooijClearData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI
 * Method:    derooijDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnDeRooijJNI_derooijDelete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
