/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI */

#ifndef _Included_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI
#define _Included_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI
 * Method:    yaoNew
 * Signature: ([BII)J
 */
JNIEXPORT jlong JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI_yaoNew
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI
 * Method:    yaoSetQueryElement
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI_yaoSetQueryElement
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI
 * Method:    yaoInsertDataPart
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI_yaoInsertDataPart
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI
 * Method:    yaoInsertDataPart2
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI_yaoInsertDataPart2
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI
 * Method:    yaoComputeColumnAndClearData
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI_yaoComputeColumnAndClearData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI
 * Method:    yaoClearData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI_yaoClearData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI
 * Method:    yaoDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_enquery_encryptedquery_responder_wideskies_common_ComputeEncryptedColumnYaoJNI_yaoDelete
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
